#pragma once
// ============================================================
//  IAssetImporter — interface for all concrete asset importers.
//
//  EDITOR-ONLY — never include from runtime code.
//
//  Each asset type implements IAssetImporter and registers itself
//  with the import pipeline.  The interface is deliberately narrow:
//  the importer receives a typed context and returns an AssetMetadata
//  that the pipeline serializes to a .sasset file.
//
//  Adding a new importer:
//      class PsdImporter : public IAssetImporter { ... };
//      // Register with the pipeline at startup — no base-class changes needed.
// ============================================================

#include <filesystem>
#include <string>
#include <vector>

#include "../metadata/AssetMetadata.h"

namespace shine::editor::asset
{
    // -----------------------------------------------------------------------
    //  Context passed to IAssetImporter::Import().
    // -----------------------------------------------------------------------
    struct AssetImportContext
    {
        /// Absolute path of the source file being imported (e.g. .fbx, .png).
        std::filesystem::path sourceFile;

        /// Absolute root of the Content/ directory.
        std::filesystem::path contentRoot;

        /// Destination .sasset file path (chosen by the pipeline, not the importer).
        std::filesystem::path outputSAssetPath;

        /// UUID to assign to the root AssetRecord.
        /// Pre-generated by the pipeline so it is stable on re-import.
        std::string rootUUID;

        /// Opaque raw JSON of previously saved import settings for this asset
        /// (empty on first import).  Importers use ParseImportSettings<T>() to
        /// retrieve typed settings, then apply them.
        glz::raw_json savedImportSettings;

        /// Progress reporting callback — optional.
        /// `message` is a human-readable status string; `fraction` in [0, 1].
        std::function<void(std::string_view message, float fraction)> onProgress;
    };

    // -----------------------------------------------------------------------
    //  Import result
    // -----------------------------------------------------------------------
    struct ImportResult
    {
        bool          succeeded = false;
        AssetMetadata metadata;             // valid only when succeeded == true
        std::string   errorMessage;         // non-empty on failure

        /// Additional .sasset files produced alongside the main asset
        /// (e.g. embedded textures and materials from a GLB).
        /// Each entry: { absolute_sasset_path, AssetMetadata }.
        /// The pipeline will write and register all of these automatically.
        std::vector<std::pair<std::filesystem::path, AssetMetadata>> sideAssets;
    };

    // -----------------------------------------------------------------------
    //  IAssetImporter
    // -----------------------------------------------------------------------
    class IAssetImporter
    {
    public:
        virtual ~IAssetImporter() = default;

        /// Return the human-readable name of this importer (e.g. "FBX Model Importer").
        [[nodiscard]] virtual std::string_view GetName() const noexcept = 0;

        /// Return the file extensions this importer can handle (lower-case, with dot).
        /// e.g. { ".fbx", ".obj", ".gltf", ".glb" }
        [[nodiscard]] virtual std::vector<std::string_view>
        SupportedExtensions() const noexcept = 0;

        /// Return true if this importer can handle `sourceFile`.
        /// Default implementation checks SupportedExtensions(); override for
        /// content-based detection (e.g. magic-byte sniffing).
        [[nodiscard]] virtual bool
        CanImport(const std::filesystem::path& sourceFile) const noexcept;

        /// Perform the import.  Called on a worker thread — must be thread-safe.
        /// The returned AssetMetadata is serialized to a .sasset file by the pipeline.
        [[nodiscard]] virtual ImportResult
        Import(const AssetImportContext& ctx) = 0;

        /// Render ImGui controls for this importer's type-specific settings.
        ///
        /// `inOutSettings` carries the current settings as a raw JSON blob
        /// (empty on first import).  Implementations parse it with
        /// ParseImportSettings<T>(), render their widgets, and on any change
        /// re-serialize back with SerializeImportSettings<T>().
        ///
        /// Called every frame while the import dialog is open.
        /// Default: no-op (returns false).  Override in concrete importers.
        virtual bool RenderImportSettingsUI(glz::raw_json& inOutSettings);
    };

    // -----------------------------------------------------------------------
    //  Default CanImport — extension matching
    // -----------------------------------------------------------------------
    inline bool IAssetImporter::CanImport(const std::filesystem::path& sourceFile) const noexcept
    {
        std::string ext = sourceFile.extension().string();
        // Normalize to lower-case
        for (char& c : ext) c = static_cast<char>(std::tolower(static_cast<unsigned char>(c)));
        for (std::string_view supported : SupportedExtensions())
            if (ext == supported)
                return true;
        return false;
    }

    inline bool IAssetImporter::RenderImportSettingsUI(glz::raw_json& /*inOutSettings*/)
    {
        return false; // No settings UI by default
    }

} // namespace shine::editor::asset
